# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

# Use a package of configuration called an orb, see https://circleci.com/docs/2.0/orb-intro/
orbs:
  # Declare a dependency on the welcome-orb
  welcome: circleci/welcome-orb@0.3.1

jobs:
  build:
    docker:
      - image: circleci/node:8-browsers # comes with Java8
    steps:
      - checkout
      - run: node -v
      - run: python -V
      - run: cp config/ci.config.json config/project.json
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - run: cd packages/messaging && yarn test
      - run: echo "finsihed build"

# Orchestrate or schedule a set of jobs, see https://circleci.com/docs/2.0/workflows/
workflows:
  # Name the workflow "Welcome"
  Welcome:
    # Run the welcome/run job in its own container
    jobs:
      - welcome/run
      - build